<script lang="ts">
  import { createEventDispatcher, tick } from 'svelte'; import type { NoticePage } from '../stores/notifications'; import { IconFavorite } from '../lib/ui/icons';
  export let open=false; let query=''; let input:HTMLInputElement; let favorites:string[]=[]; const dispatch=createEventDispatcher<{close:void;navigate:NoticePage}>();
  type Entry={label:string;detail:string;page:NoticePage};
  const entries:Entry[]=[['DASHBOARD','System and ARGUS overview','dashboard'],['ACTIVE TASKS','Current task and plan state','tasks'],['AGENTS','Active state and plan visibility','agents'],['MODULES','Backend-derived module health','modules'],['SECURITY','Posture, threats, audit, and session','security'],['LOGS','Bounded normalized event history','logs'],['TOOLS','Supported quick actions and system views','tools'],['SETTINGS','Backend-owned configuration','settings']].map(([label,detail,page])=>({label,detail,page:page as NoticePage}));
  $: matches=entries.filter((entry)=>`${entry.label} ${entry.detail}`.toLowerCase().includes(query.toLowerCase()));
  $: ordered=[...matches].sort((a,b)=>Number(favorites.includes(b.label))-Number(favorites.includes(a.label)));
  $: if(open) { try{favorites=JSON.parse(localStorage.getItem('argus-hud-favorites')||'[]');}catch{favorites=[];} tick().then(()=>input?.focus()); }
  function choose(page:NoticePage){query='';dispatch('navigate',page);dispatch('close');}
  function toggle(label:string){favorites=favorites.includes(label)?favorites.filter((item)=>item!==label):[...favorites,label]; try{localStorage.setItem('argus-hud-favorites',JSON.stringify(favorites));}catch{/* private browsing or quota -- the in-memory toggle still works this session */}}
  function key(event:KeyboardEvent){if(event.key==='Escape')dispatch('close'); if(event.key==='Enter'&&ordered[0]) choose(ordered[0].page);} function backdrop(event:MouseEvent){if(event.target===event.currentTarget)dispatch('close');}
</script>
{#if open}<div class="palette-backdrop" role="presentation" on:click={backdrop}><div class="command-palette panel" role="dialog" aria-modal="true" aria-label="Command palette"><header><b>COMMAND PALETTE</b><small>DESTINATIONS · CTRL+K</small></header><input bind:this={input} bind:value={query} on:keydown={key} placeholder="Search pages, modules, tools, settings…" aria-label="Search ARGUS destinations" />{#if ordered.length}<div>{#each ordered as entry}<div class="palette-row"><button on:click={()=>choose(entry.page)}><b>{entry.label}</b><span>{entry.detail}</span></button><button class="favorite" aria-label={`Toggle ${entry.label} favorite`} on:click={()=>toggle(entry.label)}><IconFavorite size={16} weight={favorites.includes(entry.label)?'fill':'regular'} aria-hidden="true"/></button></div>{/each}</div>{:else}<p>NO MATCHING REAL DESTINATION</p>{/if}</div></div>{/if}
