<script lang="ts">
  import { onMount } from 'svelte'; import { getSettings, resetSetting, saveSetting, type SettingField } from '../services/api';
  let fields: SettingField[]=[]; let error=''; let busy=''; let restart:string[]=[];
  async function load(){try{const data=await getSettings();fields=Array.isArray(data.fields)?data.fields:[];restart=data.needs_restart ?? [];}catch{error='Settings are unavailable from the backend.';}}
  function coerce(field:SettingField,event:Event):string|number|boolean|undefined{const target=event.currentTarget as HTMLInputElement;if(typeof field.value==='boolean')return target.checked;if(typeof field.value==='number'){const n=Number(target.value);return Number.isFinite(n)?n:undefined;}return target.value;}
  async function save(field:SettingField,event:Event){const value=coerce(field,event);if(value===undefined){error='Enter a valid number.';return;}busy=field.name;error='';try{const result=await saveSetting(field.name,value);if(result.rejected?.length)error=result.rejected[0].reason ?? 'Setting was rejected.';else{await load();}}catch{error='Setting could not be saved.';}finally{busy='';}}
  async function reset(field:SettingField){busy=field.name;error='';try{await resetSetting(field.name);await load();}catch{error='Setting could not be reset.';}finally{busy='';}}
  onMount(()=>{void load();});
</script>
<section class:settings-empty={!fields.length} class="settings-page panel"><div class="panel-title"><h2>SETTINGS</h2><span class="status">BACKEND CATALOGUE</span></div>{#if error}<p class="auth-error" role="alert">{error}</p>{/if}{#if restart.length}<p class="settings-note">RESTART REQUIRED: {restart.join(', ')}</p>{/if}<div class="setting-list">{#each fields as field (field.name)}<article class:locked={field.class==='locked'}><div><b>{field.label}</b><small>{field.help}</small><em>{field.class.toUpperCase()}</em></div>{#if typeof field.value==='boolean'}<input aria-label={field.label} type="checkbox" checked={field.value===true} disabled={field.class==='locked'||busy===field.name} on:change={(e)=>save(field,e)}/>{:else if typeof field.value==='number'}<input aria-label={field.label} type="number" step="any" value={field.value ?? ''} disabled={field.class==='locked'||busy===field.name} on:change={(e)=>save(field,e)}/>{:else}<input aria-label={field.label} value={field.value ?? ''} disabled={field.class==='locked'||busy===field.name} on:change={(e)=>save(field,e)}/>{/if}{#if field.class!=='locked'}<button type="button" disabled={busy===field.name} on:click={()=>reset(field)}>RESET</button>{/if}</article>{/each}{#if !fields.length && !error}<p>LOADING REAL SETTINGS…</p>{/if}</div></section>
