"""ARGUS AI City -- shared Blender asset kit.

Every asset in hud-v2/public/assets/city/ is generated by these scripts. No
hand-modelling, no downloaded packs: run `build_all.py` and the whole city
rebuilds from source. That is the point -- the assets are code, reviewable
and diffable like the rest of the repo.

Determinism is a hard requirement (a gate checks it): no randomness that is
not seeded and pure, no dict iteration order dependence, no timestamps, no
"now". Two runs from a clean tree must produce byte-identical GLBs.

Run with:
    blender --background --python tools/blender/build_all.py
"""

import bpy
import bmesh
import json
import math
import os
from mathutils import Vector, Euler

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------

# tools/blender/argus_kit.py -> repo root
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ASSET_ROOT = os.path.join(REPO_ROOT, "hud-v2", "public", "assets", "city")

ASSET_DIRS = (
    "buildings", "interiors", "props", "vegetation", "robots", "signs", "roads",
)


def ensure_dirs():
    for d in ASSET_DIRS:
        os.makedirs(os.path.join(ASSET_ROOT, d), exist_ok=True)


# --------------------------------------------------------------------------
# World scale (brief: 1 Blender unit = 1 metre = 1 Three.js unit)
# --------------------------------------------------------------------------

FLOOR_H = 3.4          # one architectural storey
DOOR_H = 2.3           # door opening height
DOOR_W = 1.6
ROBOT_H = 1.75         # mini ARGUS robot, head to floor
SIDEWALK_H = 0.22      # kerb height, matches the runtime's KERB_H


# --------------------------------------------------------------------------
# Deterministic pseudo-random
# --------------------------------------------------------------------------

def rnd(seed):
    """Deterministic value in [0,1) from an integer-ish seed. The SAME formula
    the runtime uses, so a facade generated here and a window lit at runtime
    agree when they share a seed."""
    x = math.sin(seed * 12.9898) * 43758.5453
    return x - math.floor(x)


def rnd_range(seed, lo, hi):
    return lo + rnd(seed) * (hi - lo)


def rnd_pick(seed, items):
    return items[int(rnd(seed) * len(items)) % len(items)]


# --------------------------------------------------------------------------
# Material system -- one shared palette for the whole city.
# Exported GLBs reference materials by name; the runtime can look them up to
# recolour live-state accents without touching the rest of the building.
# --------------------------------------------------------------------------

PALETTE = {
    # name:            (base rgb,             metal, rough, emit rgb or None, emit strength)
    "ARGUS_Graphite":  ((0.088, 0.108, 0.128), 0.55, 0.55, None, 0.0),
    "ARGUS_DarkAlloy": ((0.048, 0.062, 0.078), 0.72, 0.42, None, 0.0),
    "ARGUS_Steel":     ((0.185, 0.215, 0.250), 0.68, 0.45, None, 0.0),
    "ARGUS_Concrete":  ((0.125, 0.140, 0.156), 0.05, 0.86, None, 0.0),
    "ARGUS_Asphalt":   ((0.052, 0.062, 0.072), 0.05, 0.94, None, 0.0),
    "ARGUS_Sidewalk":  ((0.140, 0.162, 0.185), 0.05, 0.88, None, 0.0),
    "ARGUS_BlackGlass": ((0.030, 0.050, 0.068), 0.42, 0.14, (0.04, 0.13, 0.18), 0.55),
    "ARGUS_WarmGlass": ((0.95, 0.66, 0.38), 0.00, 0.30, (1.00, 0.68, 0.38), 3.2),
    "ARGUS_CoolGlass": ((0.42, 0.78, 0.92), 0.00, 0.30, (0.42, 0.80, 0.94), 2.0),
    "ARGUS_Cyan":      ((0.22, 0.88, 1.00), 0.00, 0.35, (0.22, 0.88, 1.00), 4.0),
    "ARGUS_White":     ((0.86, 0.93, 1.00), 0.00, 0.35, (0.86, 0.93, 1.00), 3.0),
    "ARGUS_Purple":    ((0.65, 0.55, 0.98), 0.00, 0.35, (0.65, 0.55, 0.98), 2.6),
    # District signal colours (visual design: the city must separate by hue,
    # not all read as one cyan).
    "ARGUS_Teal":      ((0.16, 0.82, 0.74), 0.00, 0.35, (0.16, 0.84, 0.76), 3.2),
    "ARGUS_Violet":    ((0.58, 0.46, 1.00), 0.00, 0.35, (0.60, 0.48, 1.00), 3.0),
    "ARGUS_SoftBlue":  ((0.44, 0.66, 1.00), 0.00, 0.35, (0.46, 0.68, 1.00), 2.4),
    "ARGUS_Lime":      ((0.62, 0.92, 0.42), 0.00, 0.35, (0.62, 0.92, 0.42), 2.6),
    "ARGUS_Amber":     ((1.00, 0.70, 0.27), 0.00, 0.35, (1.00, 0.70, 0.27), 3.0),
    "ARGUS_Red":       ((1.00, 0.29, 0.29), 0.00, 0.35, (1.00, 0.29, 0.29), 3.0),
    "ARGUS_Foliage":   ((0.075, 0.180, 0.150), 0.00, 0.92, None, 0.0),
    "ARGUS_FoliageDark": ((0.048, 0.135, 0.118), 0.00, 0.94, None, 0.0),
    "ARGUS_Trunk":     ((0.085, 0.075, 0.060), 0.00, 0.95, None, 0.0),
    "ARGUS_RobotBody": ((0.075, 0.092, 0.105), 0.70, 0.45, None, 0.0),
    "ARGUS_RobotJoint": ((0.030, 0.042, 0.052), 0.85, 0.35, None, 0.0),
    "ARGUS_RobotPlate": ((0.115, 0.140, 0.162), 0.72, 0.40, None, 0.0),
    "ARGUS_Visor":     ((0.22, 0.88, 1.00), 0.00, 0.20, (0.22, 0.88, 1.00), 6.0),
    "ARGUS_ScreenOn":  ((0.28, 0.70, 0.85), 0.00, 0.30, (0.30, 0.74, 0.90), 2.4),
    "ARGUS_ScreenOff": ((0.030, 0.045, 0.055), 0.20, 0.30, None, 0.0),
}


# --------------------------------------------------------------------------
# DISTRICT COLOUR SEPARATION
#
# The single biggest readability problem with the first city was that every
# building shared one graphite+cyan palette, so the whole scene sank into the
# dark navy HUD behind it. The fix is not "more neon": it is giving each
# district category its own HUE and VALUE band, so districts separate from
# each other and from the UI while staying inside one premium ARGUS language.
#
# Each family supplies (hue-tint rgb multiplier, value lift, accent material).
# Structural materials are tinted through this; emissive accents stay pure.
# --------------------------------------------------------------------------

FAMILY_TINTS = {
    # family:        (tint multiplier r,g,b),        value lift, accent,          second accent
    #
    # These are deliberately STRONG. A subtle tint is invisible once the
    # runtime's night lighting darkens everything again -- the districts have
    # to separate from each other AND from the navy HUD behind the canvas.
    # The value lift matters as much as the hue: it pulls each family off the
    # background's own brightness so silhouettes stay readable.
    "corporate":     ((0.74, 0.96, 1.42), 0.052, "ARGUS_Cyan", "ARGUS_White"),
    "hardened":      ((1.34, 0.86, 0.88), 0.040, "ARGUS_Teal", "ARGUS_Red"),
    "academic":      ((1.06, 0.84, 1.52), 0.060, "ARGUS_Violet", "ARGUS_Cyan"),
    "industrial":    ((1.54, 1.06, 0.62), 0.054, "ARGUS_Amber", "ARGUS_Cyan"),
    "residential":   ((0.92, 1.06, 1.30), 0.086, "ARGUS_SoftBlue", "ARGUS_WarmGlass"),
    "civic":         ((1.10, 1.18, 1.30), 0.098, "ARGUS_White", "ARGUS_Cyan"),
    "cloud":         ((1.22, 0.92, 1.46), 0.058, "ARGUS_Amber", "ARGUS_Violet"),
    "utility":       ((1.24, 1.10, 0.86), 0.038, "ARGUS_Amber", "ARGUS_Cyan"),
    "neutral":       ((1.00, 1.00, 1.00), 0.000, "ARGUS_Cyan", "ARGUS_White"),
}

# Only STRUCTURAL materials get tinted -- an emissive accent must stay the
# exact signal colour it is, or state colours stop meaning anything.
TINTABLE = ("ARGUS_Graphite", "ARGUS_DarkAlloy", "ARGUS_Steel", "ARGUS_Concrete")


def family_accent(family, secondary=False):
    tint = FAMILY_TINTS.get(family, FAMILY_TINTS["neutral"])
    return tint[3] if secondary else tint[2]


def tinted_name(base, family):
    if family in (None, "neutral") or base not in TINTABLE:
        return base
    return "%s@%s" % (base, family)


def get_tinted_material(base, family):
    """Fetch-or-create the district-tinted variant of a structural material."""
    name = tinted_name(base, family)
    if name == base:
        return get_material(base)
    mat = bpy.data.materials.get(name)
    if mat is not None:
        return mat
    mul, lift, _accent, _second = FAMILY_TINTS[family]
    base_rgb, metal, rough, emit, emit_strength = PALETTE[base]
    rgb = tuple(min(1.0, base_rgb[i] * mul[i] + lift) for i in range(3))
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = _principled(mat)
    _set_input(bsdf, ["Base Color"], (rgb[0], rgb[1], rgb[2], 1.0))
    _set_input(bsdf, ["Metallic"], metal)
    _set_input(bsdf, ["Roughness"], rough)
    if emit is not None:
        _set_input(bsdf, ["Emission Color", "Emission"], (emit[0], emit[1], emit[2], 1.0))
        _set_input(bsdf, ["Emission Strength"], emit_strength)
    else:
        _set_input(bsdf, ["Emission Strength"], 0.0)
    return mat


def _principled(mat):
    return mat.node_tree.nodes.get("Principled BSDF")


def _set_input(node, names, value):
    """Blender renamed several Principled sockets across 3.x/4.x/5.x; try each
    candidate name so these scripts are not pinned to one release."""
    for n in names:
        sock = node.inputs.get(n)
        if sock is not None:
            sock.default_value = value
            return True
    return False


def get_material(name):
    """Fetch-or-create a palette material. Shared across every object in the
    file, so a GLB carries one material per palette entry it actually uses."""
    mat = bpy.data.materials.get(name)
    if mat is not None:
        return mat
    if name not in PALETTE:
        raise KeyError("unknown palette material: %s" % name)
    base, metal, rough, emit, emit_strength = PALETTE[name]
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = _principled(mat)
    _set_input(bsdf, ["Base Color"], (base[0], base[1], base[2], 1.0))
    _set_input(bsdf, ["Metallic"], metal)
    _set_input(bsdf, ["Roughness"], rough)
    if emit is not None:
        _set_input(bsdf, ["Emission Color", "Emission"], (emit[0], emit[1], emit[2], 1.0))
        _set_input(bsdf, ["Emission Strength"], emit_strength)
    else:
        _set_input(bsdf, ["Emission Strength"], 0.0)
    return mat


# --------------------------------------------------------------------------
# Scene management
# --------------------------------------------------------------------------

def reset_scene():
    """Empty factory scene: no default cube, camera or light in the export."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    # Purge orphaned datablocks so repeated builds in one process cannot leak
    # a previous asset's mesh into the next export.
    bpy.ops.outliner.orphans_purge(do_local_ids=True, do_linked_ids=True, do_recursive=True)


def new_collection(name):
    col = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(col)
    return col


# --------------------------------------------------------------------------
# Mesh building -- everything goes through bmesh so we get real geometry ops
# (inset, bevel, solidify) instead of bare primitives.
# --------------------------------------------------------------------------

class Part:
    """An accumulating bmesh with one material. Parts are merged per material
    at the end, which is what keeps a whole building at 1-6 draw calls."""

    def __init__(self, material, family=None):
        self.material = material
        self.family = family
        self.bm = bmesh.new()

    def _absorb(self, bm):
        """Merge a scratch bmesh into this part, then free BOTH it and the
        temporary mesh datablock. Without the explicit remove(), a city's
        worth of boxes leaks tens of thousands of mesh datablocks and the
        build slows to a crawl."""
        mesh = bpy.data.meshes.new("__scratch")
        bm.to_mesh(mesh)
        self.bm.from_mesh(mesh)
        bpy.data.meshes.remove(mesh)
        bm.free()

    def box(self, cx, cy, cz, sx, sy, sz, bevel=0.0):
        """A box centred at (cx,cy,cz) with full sizes (sx,sy,sz). Blender is
        Z-up; the glTF exporter converts to the Y-up the runtime expects."""
        bm = bmesh.new()
        bmesh.ops.create_cube(bm, size=1.0)
        bmesh.ops.scale(bm, vec=Vector((sx, sy, sz)), verts=bm.verts)
        if bevel > 0:
            bmesh.ops.bevel(bm, geom=list(bm.verts) + list(bm.edges),
                            offset=bevel, segments=1, affect="EDGES", clamp_overlap=True)
        bmesh.ops.translate(bm, vec=Vector((cx, cy, cz)), verts=bm.verts)
        self._absorb(bm)
        return self

    def cyl(self, cx, cy, cz, r_top, r_bot, h, segs=12, bevel=0.0):
        bm = bmesh.new()
        bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=segs,
                              radius1=r_bot, radius2=r_top, depth=h)
        if bevel > 0:
            bmesh.ops.bevel(bm, geom=list(bm.verts) + list(bm.edges),
                            offset=bevel, segments=1, affect="EDGES", clamp_overlap=True)
        bmesh.ops.translate(bm, vec=Vector((cx, cy, cz)), verts=bm.verts)
        self._absorb(bm)
        return self

    def prism(self, cx, cy, cz, r, h, segs=6, rot_z=0.0, bevel=0.0):
        return self.cyl(cx, cy, cz, r, r, h, segs=segs, bevel=bevel) if rot_z == 0 else \
            self._prism_rot(cx, cy, cz, r, h, segs, rot_z, bevel)

    def _prism_rot(self, cx, cy, cz, r, h, segs, rot_z, bevel):
        bm = bmesh.new()
        bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=segs,
                              radius1=r, radius2=r, depth=h)
        bmesh.ops.rotate(bm, verts=bm.verts, cent=Vector((0, 0, 0)),
                         matrix=Euler((0, 0, rot_z)).to_matrix())
        if bevel > 0:
            bmesh.ops.bevel(bm, geom=list(bm.verts) + list(bm.edges),
                            offset=bevel, segments=1, affect="EDGES", clamp_overlap=True)
        bmesh.ops.translate(bm, vec=Vector((cx, cy, cz)), verts=bm.verts)
        self._absorb(bm)
        return self

    def frame(self, cx, cy, cz, sx, sy, sz, thickness):
        """A rectangular picture-frame ring in the XZ plane -- the facade
        element that reads as a structural surround rather than a flat panel."""
        t = thickness
        self.box(cx, cy, cz + sz / 2 - t / 2, sx, sy, t)
        self.box(cx, cy, cz - sz / 2 + t / 2, sx, sy, t)
        self.box(cx - sx / 2 + t / 2, cy, cz, t, sy, sz - 2 * t)
        self.box(cx + sx / 2 - t / 2, cy, cz, t, sy, sz - 2 * t)
        return self

    def to_object(self, name, collection):
        mesh = bpy.data.meshes.new(name)
        bmesh.ops.remove_doubles(self.bm, verts=self.bm.verts, dist=1e-5)
        self.bm.normal_update()
        self.bm.to_mesh(mesh)
        self.bm.free()
        self.bm = None
        mesh.materials.append(get_tinted_material(self.material, self.family))
        for poly in mesh.polygons:
            poly.use_smooth = False   # flat-shaded stylized look
        obj = bpy.data.objects.new(name, mesh)
        collection.objects.link(obj)
        return obj


class Builder:
    """Collects geometry into one Part per material, then emits one object per
    material. A building therefore costs as many draw calls as it uses
    distinct materials -- typically 4-6, not one per box."""

    def __init__(self, name, family="neutral"):
        self.name = name
        # The district category this building belongs to. Every STRUCTURAL
        # material requested through m() is resolved to that family's tinted
        # variant, so a whole family shifts hue from one argument instead of
        # every call site naming a colour (visual design).
        self.family = family
        self.parts = {}
        self._order = []

    def m(self, material):
        if material not in self.parts:
            self.parts[material] = Part(material, self.family)
            self._order.append(material)
        return self.parts[material]

    def accent(self, secondary=False):
        """This family's signal colour -- use instead of hard-coding cyan."""
        return family_accent(self.family, secondary)

    def emit(self, collection):
        objs = []
        for material in self._order:          # insertion order == deterministic
            part = self.parts[material]
            if len(part.bm.verts) == 0:
                part.bm.free()
                continue
            name = "%s_%s" % (self.name, tinted_name(material, self.family).replace("ARGUS_", ""))
            objs.append(part.to_object(name, collection))
        return objs


# --------------------------------------------------------------------------
# Reusable architectural modules (real floors, slabs, wall
# thickness, windows, doors, parapets, columns, entrances, rooftop plant)
# --------------------------------------------------------------------------

def window_grid(b, x0, x1, z0, z1, y, depth, seed, cols=None, rows=None,
                lit_ratio=0.22, cool_ratio=0.10, recess=0.12):
    """A band of recessed windows on a facade plane at `y`, facing -Y or +Y
    depending on the sign of `depth`. Dark glass everywhere, a seeded subset
    warm-lit and a smaller subset cool-lit, so no two facades light the same
    and nothing ever flickers (the choice is baked into geometry)."""
    w = x1 - x0
    h = z1 - z0
    if w <= 0.4 or h <= 0.3:
        return
    cols = cols or max(1, int(w / 1.9))
    rows = rows or max(1, int(h / 1.6))
    cw = (w / cols) * 0.62
    ch = (h / rows) * 0.60
    for r in range(rows):
        for c in range(cols):
            cx = x0 + (c + 0.5) * (w / cols)
            cz = z0 + (r + 0.5) * (h / rows)
            s = seed + r * 37 + c * 13
            roll = rnd(s)
            if roll > 1.0 - lit_ratio:
                mat = "ARGUS_WarmGlass"
            elif roll < cool_ratio:
                mat = "ARGUS_CoolGlass"
            else:
                mat = "ARGUS_BlackGlass"
            # Reveal (the dark surround) then the glass itself, set back into
            # it -- this is what gives a facade depth at grazing light.
            b.m("ARGUS_DarkAlloy").box(cx, y + depth * 0.5, cz, cw + 0.14, abs(depth), ch + 0.14)
            b.m(mat).box(cx, y + depth * recess, cz, cw, abs(depth) * 0.35, ch)


def floor_band(b, cx, cy, w, d, z, thickness=0.26, overhang=0.10, mat="ARGUS_Steel"):
    """A floor slab that reads from outside as a horizontal shadow line."""
    b.m(mat).box(cx, cy, z, w + overhang * 2, d + overhang * 2, thickness, bevel=0.02)


def corner_columns(b, cx, cy, w, d, z0, z1, size=0.42, mat="ARGUS_DarkAlloy"):
    h = z1 - z0
    for sx in (-1, 1):
        for sy in (-1, 1):
            b.m(mat).box(cx + sx * (w / 2 - size / 2), cy + sy * (d / 2 - size / 2),
                         z0 + h / 2, size, size, h, bevel=0.03)


def parapet(b, cx, cy, w, d, z, height=0.75, thickness=0.30, mat="ARGUS_Concrete"):
    """A real roof edge wall -- the single cheapest thing that stops a roof
    reading as the flat top of a box."""
    for sy in (-1, 1):
        b.m(mat).box(cx, cy + sy * (d / 2 - thickness / 2), z + height / 2, w, thickness, height, bevel=0.02)
    for sx in (-1, 1):
        b.m(mat).box(cx + sx * (w / 2 - thickness / 2), cy, z + height / 2,
                     thickness, d - thickness * 2, height, bevel=0.02)


def entrance(b, cx, cy, w, z0, face=-1, accent="ARGUS_Cyan", canopy=True):
    """A ground-floor entrance at real door scale: recessed reveal, glazed
    doors, a canopy and a light strip. This is the scale reference that tells
    a viewer how big the whole building is."""
    y = cy + face * 0.0
    b.m("ARGUS_DarkAlloy").box(cx, y, z0 + (DOOR_H + 0.7) / 2, w + 0.9, 0.55, DOOR_H + 0.7)
    b.m("ARGUS_WarmGlass").box(cx, y + face * 0.24, z0 + DOOR_H / 2, w, 0.14, DOOR_H)
    b.m("ARGUS_Steel").box(cx, y + face * 0.24, z0 + DOOR_H / 2, 0.10, 0.18, DOOR_H)
    if canopy:
        b.m("ARGUS_Steel").box(cx, y + face * 0.85, z0 + DOOR_H + 0.62, w + 1.8, 1.7, 0.16, bevel=0.03)
        b.m(accent).box(cx, y + face * 1.62, z0 + DOOR_H + 0.54, w + 1.5, 0.07, 0.07)
    # Steps up from the pavement.
    for i in range(2):
        b.m("ARGUS_Concrete").box(cx, y + face * (0.9 + i * 0.45), z0 - 0.06 - i * 0.11,
                                  w + 1.6 - i * 0.3, 0.9, 0.12)


def roof_plant(b, cx, cy, w, d, z, seed, accent="ARGUS_Cyan"):
    """Rooftop HVAC, vents, a stair head and an antenna. Rooflines are what an
    isometric camera sees most of -- an empty one reads as an unfinished box."""
    units = 2 if w < 9 else 3
    for i in range(units):
        ux = cx - w * 0.26 + (i * w * 0.52) / max(1, units - 1)
        uy = cy + (rnd(seed + i * 7) - 0.5) * d * 0.4
        uw = 1.1 + rnd(seed + i) * 0.7
        b.m("ARGUS_Steel").box(ux, uy, z + 0.42, uw, 1.35, 0.84, bevel=0.03)
        b.m("ARGUS_DarkAlloy").cyl(ux, uy, z + 0.90, 0.30, 0.30, 0.10, segs=8)
    # Stair / lift head -- the little block that makes a roof believable.
    b.m("ARGUS_Concrete").box(cx + w * 0.28, cy - d * 0.26, z + 1.15, 2.1, 2.1, 2.3, bevel=0.03)
    b.m(accent).box(cx + w * 0.28, cy - d * 0.26 - 1.06, z + 1.9, 1.2, 0.06, 0.06)
    # Vent stack.
    b.m("ARGUS_Steel").cyl(cx - w * 0.30, cy + d * 0.26, z + 0.75, 0.30, 0.36, 1.5, segs=8)


def antenna(b, cx, cy, z, h, accent="ARGUS_Cyan", dish=True):
    b.m("ARGUS_Steel").cyl(cx, cy, z + h / 2, 0.07, 0.11, h, segs=6)
    if dish:
        b.m("ARGUS_Steel").cyl(cx, cy, z + h * 0.78, 0.36, 0.12, 0.10, segs=10)
    b.m(accent).cyl(cx, cy, z + h + 0.06, 0.09, 0.09, 0.12, segs=6)


def light_strip(b, cx, cy, w, d, z, accent="ARGUS_Cyan", t=0.07):
    """A thin emissive line around a mass -- the city's main light language.
    Never a glowing wall (accents, not paint)."""
    for sy in (-1, 1):
        b.m(accent).box(cx, cy + sy * d / 2, z, w, t, t)
    for sx in (-1, 1):
        b.m(accent).box(cx + sx * w / 2, cy, z, t, d, t)


def sign_plate(b, cx, cy, cz, w, h, face=-1, accent="ARGUS_Cyan"):
    """A physically-mounted sign: a dark backing plate standing off the wall
    with an emissive face. Text is applied at runtime as a canvas texture on
    the emissive face's own quad (no giant DOM labels)."""
    b.m("ARGUS_DarkAlloy").box(cx, cy, cz, w + 0.3, 0.16, h + 0.3)
    b.m(accent).box(cx, cy + face * 0.13, cz, w, 0.06, h)
    for sx in (-1, 1):
        b.m("ARGUS_Steel").box(cx + sx * (w / 2 + 0.05), cy + face * -0.10, cz, 0.08, 0.22, 0.08)


# --------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------

MANIFEST = []


def _tri_count(objs):
    total = 0
    for o in objs:
        if o.type != "MESH":
            continue
        me = o.data
        for poly in me.polygons:
            total += max(0, len(poly.vertices) - 2)
    return total


def export_glb(objs, subdir, name, extras=None):
    """Export the given objects as one optimized GLB and record it in the
    build manifest the runtime and the budget gate both read."""
    ensure_dirs()
    for o in bpy.context.scene.objects:
        o.select_set(False)
    real = [o for o in objs if o is not None]
    for o in real:
        o.select_set(True)
    if real:
        bpy.context.view_layer.objects.active = real[0]

    path = os.path.join(ASSET_ROOT, subdir, name + ".glb")
    kwargs = dict(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_texcoords=False,
        export_normals=True,
        export_tangents=False,
        export_materials="EXPORT",
        export_cameras=False,
        export_lights=False,
        export_extras=True,
    )
    # Animation flags only exist on newer exporters; pass what this build has.
    if extras and extras.get("animations"):
        kwargs.update(
            export_animations=True,
            export_animation_mode="ACTIONS",
            export_bake_animation=True,
            export_optimize_animation_size=True,
            export_frame_range=False,
        )
    else:
        kwargs.update(export_animations=False)

    _call_gltf_export(kwargs)

    tris = _tri_count(real)
    size = os.path.getsize(path)
    entry = {
        "file": "%s/%s.glb" % (subdir, name),
        "name": name,
        "triangles": tris,
        "bytes": size,
        "objects": len(real),
    }
    if extras:
        entry.update({k: v for k, v in sorted(extras.items()) if k != "animations"})
        if extras.get("animations"):
            entry["animations"] = sorted(extras["animations"])
    MANIFEST.append(entry)
    print("EXPORTED %-42s tris=%-7d bytes=%d" % (entry["file"], tris, size))
    return path


def _call_gltf_export(kwargs):
    """Blender's glTF operator drops/renames keywords between releases; retry
    without the unknown ones rather than pinning to a single Blender build."""
    while True:
        try:
            bpy.ops.export_scene.gltf(**kwargs)
            return
        except TypeError as exc:
            msg = str(exc)
            bad = None
            for key in list(kwargs.keys()):
                if key != "filepath" and key in msg:
                    bad = key
                    break
            if bad is None:
                raise
            print("  (exporter has no '%s' on this Blender build; skipping it)" % bad)
            kwargs.pop(bad)


def write_manifest():
    """A stable, sorted manifest -- the runtime's asset registry and the
    budget/determinism gates all read this one file."""
    ensure_dirs()
    path = os.path.join(ASSET_ROOT, "manifest.json")
    payload = {
        "generator": "tools/blender/build_all.py",
        "scale": "1 unit = 1 metre",
        "assets": sorted(MANIFEST, key=lambda e: e["file"]),
        "totals": {
            "files": len(MANIFEST),
            "triangles": sum(e["triangles"] for e in MANIFEST),
            "bytes": sum(e["bytes"] for e in MANIFEST),
        },
    }
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print("MANIFEST %s  files=%d tris=%d bytes=%d" % (
        path, payload["totals"]["files"], payload["totals"]["triangles"], payload["totals"]["bytes"]))
    return path
